Doctor
ITA-Dnipro/Dp-210_Go pull request #20
Opened 2021-08-25 15:16 UTC by KekemonBS

Created doctor CRUD.

Changed entites, handlers, usecases and router.go.

2021-08-26 20:34 UTC, glbter requested changes
well done!!!

2021-08-26 20:34 UTC, glbter commented on internal/repository/postgres/doctor/repo.go
> +		&d.ID,
looks like an error, the id should not change

2021-08-26 20:34 UTC, glbter commented on internal/entity/doctor.go
> +	StartAt    time.Time `json:"start_at"`
I can't get it. For now we are assuming, that the doctor has a fixed schedule?

2021-08-26 20:34 UTC, glbter commented on internal/server/http/handlers/doctor/handlers.go
> +		h.writeErrorResponse(http.StatusInternalServerError, err.Error(), w)
please, don't expose internal error to users

2021-08-26 20:34 UTC, glbter commented on internal/server/http/handlers/doctor/handlers.go
> +		if errors.Is(err, customerrors.NotFound) {
you could check `error.Is` before `err != nil` to remove nesting

2021-09-01 12:48 UTC, KekemonBS commented on internal/entity/doctor.go
> +	StartAt    time.Time `json:"start_at"`
yes

2021-09-01 13:32 UTC, glbter approved these changes

2021-09-01 13:35 UTC, merged